# Generated by Django 5.2.3 on 2025-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#FFE4E1', 'Pink'), ('#E0FFFF', 'Light Cyan'), ('#F5F5DC', 'Beige'), ('#E6E6FA', 'Lavender'), ('#F0FFF0', 'Honeydew')], default='#FFE4E1', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
